// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations require a DIRECT connection — not the PgBouncer pooler.
    // DATABASE_URL uses port 6543 + ?pgbouncer=true which blocks DDL.
    // DIRECT_URL uses port 5432 (session-mode pooler) which supports migrations.
    url: process.env["DIRECT_URL"],
  },
});
